import { Injectable } from '@nestjs/common';
import { Book } from '../model/book.model';
import { FindBookByIdResponseDto } from '../use-cases/find-by-id/find-book-by-id-response.dto';
import { SaveBookRequestDto } from '../use-cases/save/save-book-request.dto';
import { SaveBookResponseDto } from '../use-cases/save/save-book-response.dto';
import { UpdateBookRequestDto } from '../use-cases/update/update-book-request.dto';
import { UpdateBookResponseDto } from '../use-cases/update/update-book-response.dto';
import { FindBooksResponseDto } from '../use-cases/find-all/find-books-response.dto';

@Injectable()
export class BookMapper {
  toFindByIdResponse(book: Book): FindBookByIdResponseDto {
    return {
      id: book.id,
      title: book.title,
      author: book.author,
      price: book.price,
      isbn: book.isbn,
      publisher: book.publisher,
      availability: book.availability,
      quantity: book.quantity,
    };
  }

  fromSaveBookRequest(request: SaveBookRequestDto): Book {
    return {
      id: undefined, // ID will be generated by the repository
      title: request.title,
      author: request.author,
      price: Number(request.price),
      isbn: request.isbn,
      publisher: request.publisher,
      availability: true, // Assuming new books are available by default
      quantity: Number(request.quantity),
    };
  }

  toSaveBookResponse(book: Book): SaveBookResponseDto {
    return {
      id: book.id,
      title: book.title,
      author: book.author,
      price: book.price,
      isbn: book.isbn,
      publisher: book.publisher,
      availability: book.availability,
      quantity: book.quantity,
    };
  }

  fromUpdateBookRequest(request: UpdateBookRequestDto, id: string): Book {
    return {
      id: id,
      title: request.title,
      author: request.author,
      price: Number(request.price),
      isbn: request.isbn,
      publisher: request.publisher,
      availability: true, // Assuming updated books remain available
      quantity: Number(request.quantity),
    };
  }

  toUpdateBookResponse(book: Book): UpdateBookResponseDto {
    return {
      id: book.id,
      title: book.title,
      author: book.author,
      price: book.price,
      isbn: book.isbn,
      publisher: book.publisher,
      availability: book.availability,
      quantity: book.quantity,
    };
  }

  toFindAllResponse(books: Book[]): FindBooksResponseDto {
    return {
      books: books.map((book) => this.toFindByIdResponse(book)),
    };
  }
}
